import streamlit as st

st.set_page_config(page_title="Terms & Privacy - Verba", page_icon="📜", layout="centered")

st.title("📜 Terms of Service & Privacy Policy")
st.write("利用規約およびプライバシーポリシー (Terms of Service and Privacy Policy)")

st.markdown("---")

# Official Terms of Service & Privacy Policy content
text = """
# Terms of Service and Privacy Policy

## Terms of Service

**1. Service & AI Disclaimer**
* **Not an Official JLPT Product:** "Verba" is an independent learning platform and is not affiliated with the Japan Educational Exchanges and Services (JEES) or the Japan Foundation.
* **No Guarantee of Passing:** Using this service does not guarantee passing the JLPT or improving language proficiency.
* **AI Hallucinations:** Questions and explanations are generated by AI. They may contain inaccuracies, grammatical errors, or inappropriate expressions. We do not guarantee complete accuracy.

**2. Web3 & VRB Token Risks**
* **Not a Financial Instrument:** VRB tokens are utility tokens designed solely for use within the Verba ecosystem. They are NOT financial instruments, investments, currencies, or securities.
* **No Value Guarantee:** We do not guarantee any fiat value, future value, or exchange listing for VRB tokens. Users accept the risk that the tokens may have zero financial value.
* **Wallet Security:** Managing your wallet (e.g., MetaMask) and seed phrases to receive tokens is entirely your responsibility. We will not compensate or reissue tokens for lost access, hacks, or transfers to incorrect addresses.
* **Smart Contract Risks:** We are not liable for any damages caused by blockchain technology vulnerabilities, smart contract bugs, or network delays/outages.

**3. Accounts & Prohibited Conduct**
We reserve the right to permanently suspend accounts and forfeit all earned VRB tokens without prior notice if the following behaviors are detected:
* **Multiple Accounts:** Creating multiple accounts to unfairly earn tokens.
* **Botting & Cheating:** Using scripts, bots, macros, or other automated means to exploit the "Learn-to-Earn" system.
* **Account Sharing:** Sharing, selling, or transferring your account or premium access to third parties.

**4. Payments & Refunds**
Due to the digital nature of the content and services (including the Founder's Pack), all payments processed via PayPal are **strictly non-refundable**.

**5. Service Interruption & Termination**
We reserve the right to suspend, modify, or terminate all or part of the service without prior notice due to AI API outages, blockchain maintenance, or operational reasons. We are not liable for any damages resulting from such interruptions.

---

## Privacy Policy

**1. Data We Collect**
* **Account Information:** Email address, Discord ID, etc.
* **Web3 Information:** Wallet address (e.g., MetaMask).
* **Learning Data:** JLPT study history, quiz accuracy data, and input prompts to the AI.

**2. Blockchain Immutability**
Wallet addresses and token transaction histories provided by users are permanently recorded as public data on the blockchain. Users understand and agree that it is **technically impossible for us to delete or modify this on-chain data**.

**3. Third-Party Services**
We may share necessary data with the following third parties to provide our services:
* **Payment Providers:** PayPal (for payment processing).
* **AI Providers:** OpenAI API, etc. (learning data may be anonymized and sent for question generation and grading).
* **Analytics Tools:** Tools to analyze and improve app usage.

**4. Data Retention & Deletion**
Users may request the deletion of their accounts and personal information. However, data required for legal compliance, dispute resolution, or data already recorded on the blockchain are exempt from deletion.
"""

st.markdown(f'<div style="height: 500px; overflow-y: scroll; padding: 15px; border: 1px solid #ddd; border-radius: 8px; background-color: #f9f9f9; color: #333;">{text}</div>', unsafe_allow_html=True)

st.markdown("---")
col1, col2 = st.columns([1, 1])
with col1:
    st.page_link("app.py", label="Back to Main Page", icon="🏠")
with col2:
    st.info("Please contact support if you have any questions regarding these terms.")
